### ISSUE TITLE
trained model available?

### ISSUE THREAD

**Issue by juliechchang** [sshleifer/object_detection_kitti#6]
Hello, do you still have the best-performing model you trained, and would you be willing to share it? It sounds like you trained for 40 hours, and I'd like to skip this if possible! Thanks. The one in the TF model zoo appears to only be trained on the car category.

**Comment by sshleifer** [comment]
No, I wish I did. If you train something would be happy to post/store it in a public place for you!

617.966.4327

Leave Me Anonymous Feedback ( http://goo.gl/forms/ZTlmFBBTHq )

Sent via Superhuman ( https://sprh.mn/?vip=sshleifer@gmail.com )
